### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by NitroXenon** [horato/IntWarsSharp#1]
No commit for almost 2 months.
It seems that the porting has not finished yet...

**Comment by horato** [comment]
I don't think I am going to continue in this. I don't want to continue with it, its spaghetti anyway. Alot of stuff could be done better and I don't have enough knowledge to fix some of the broken things.

I can give you commit rights or move the project under sightstone if you want.

Oh and C++ is shit.

**Comment by NitroXenon** [comment]
My C++ sucks so I want to further develop on a full port of Intwars. I think this project (including the C++ one) is full of potential if add more features (e.g. Plugin...).

Eddy decided to make a C# port of Intwars but he discontinued it. Maybe he can fork your port and develop base on it.

**Comment by NitroXenon** [comment]
Btw do you know how to get a full 4.20 client? I used LoLPatcherProxy but when I start League Of Legends.exe through command line, it always crash...

**Comment by horato** [comment]
Patcher proxy is fucked up, it always bugsplats. I got it from mega or somewhere, can't find it anymore but I will try to upload it.

My c++ knowledge is 0, I just guessed what some of the code could be used for in most of the cases.

Also c++ is weird as fuck, take the KeyCheck packet for example. I was debugging it and as soon it created new instance of the keycheck class it was already filled with some data. I have no idea where it came from but they were just there. Pointers are weird.
Movement packet - there is some magic going on there with those waypoints...

**Comment by NitroXenon** [comment]
Ok I'll have a look on it first XD

**Comment by horato** [comment]
https://mega.nz/#!pFRVxBJQ!AMbsJnS9kqhvQ-tfP8QxoBikbrjlGQ4MdzNYGo0fIKM

**Comment by NitroXenon** [comment]
Thanks!!

**Comment by NitroXenon** [comment]
@horato Hay more people are willing to contribute to the C# port now. 
Dev chat on Discord : https://discord.gg/0vmmZ6VAwXB05gB6
